apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: /mongo1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: /mongo2